### ISSUE TITLE
Runtime properties are lost after commiting runtime object

### ISSUE THREAD

**Issue by nagaina** [mm-project/qt_painter#103]

**Comment by levibyte** [comment]
haaa et ka tenc ban :P

**Comment by levibyte** [comment]
Ok, I understand what's going on, and seems it's a doodook.

This bug introduced after global change in command management. 
Now interactive commands delegate commit to appropriate directive commands, but current shape creation directive commands does not have any arguments to store their attributes.

Need to add this : [

**Comment by levibyte** [comment]
fixed in #117
