### ISSUE TITLE
in some cases shapes will not add into rq properly

### ISSUE THREAD

**Issue by levibyte** [mm-project/qt_painter#159]
in some cases shapes will not add into rq properly so renderer will not draw this objects.

step to reproduce

1. ensure rendering is using working set mode ( it is by default ) 

2. execute following commands
dicmdCreateObjRectangle -brush 1 -color #000000 -fill 9 -points {(121,129);(196,208)} 
dicmdCreateObjRectangle -brush 1 -color #000000 -fill 9 -points {(264,135);(317,189)} 
dicmdCreateObjRectangle -brush 1 -color #000000 -fill 9 -points {(201,78);(259,107)}

3. switch to RQ rendering mode , see the upper box is not rendering ( no such entry in RQ )

**Comment by nagaina** [comment]
fixed in dev_merge_for_copymove
